version: '3.3'
services:
  backend:
    container_name: backend
    image: image_service
    build: .
    ports:
      - "5000:5000"
    volumes:
      - backenddata:/data/files
    environment:
      - AZURE_ACCOUNT_NAME=${AZURE_ACCOUNT_NAME}
      - AZURE_ACCOUNT_KEY=${AZURE_ACCOUNT_KEY}
      - AZURE_SHARE_NAME=${AZURE_SHARE_NAME}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB=${MONGO_DB}
      - MONGO_COLLECTION=${MONGO_COLLECTION}
      - API_KEY=${API_KEY}
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
volumes:
  mongodata:
  backenddata: